x = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(x))
print('É alfabético? ', x.isalpha())
print('É numérico? ', x.isnumeric())
print('É alfanumérico? ', x.isalnum())
print('Está em minúsculas? ', x.islower())
print('Está em maiúsculas? ', x.isupper())
print('É um número? ', x.isnumeric())
print('Só tem espaços? ', x.isspace())
