nome = str(input('Digite seu nome completo: ')).strip().title()
nomediv = nome.split()
print(f'O seu primeiro nome é {nomediv[0]}')
print(f'O seu último nome é {nomediv[-1]}')
print(nomediv[0], nomediv[-1])
